### ISSUE TITLE
Issue with image links that are having GET methods in the url bar

### ISSUE THREAD

**Issue by DontStealMyCodePls** [sindresorhus/image-type#10]
So let's say I have this piece of code
![image](https://user-images.githubusercontent.com/46570907/54542986-77367580-49a5-11e9-9ce8-62b55350fcd2.png)

And then send the next URL image to the Node Js server to check it's mime type
https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/09/12/11/naturo-monkey-selfie.jpg?w968h681

**Bug:** The function is returning **null** because of the "?w968h681" part of the url which is a GET request to resize the image.
When I remove that GET request the mime type is returned with no problems at all.

**Comment by sindresorhus** [comment]
The image is correctly detected when I download it locally, so the problem is in your logic, not `image-type`. I would not recommend trusting that the `chunk` is large enough. You should explicitly ask for a large enough chunk. See the example in the readme on how to do it correctly: https://github.com/sindresorhus/image-type#usage

**Comment by DontStealMyCodePls** [comment]
![image](https://user-images.githubusercontent.com/46570907/54613902-2e91c180-4a64-11e9-8e5a-d48488d1c286.png)
Did as it's said in your example and if I put it in a loop for over more than one image I get this error
![image](https://user-images.githubusercontent.com/46570907/54625977-f2b52700-4a78-11e9-9006-28902e80f1b7.png)
